modules:
  - import: modules.face_blur.plugin
    shortcut: b
    enabled: false

  - import: modules.fire_detection.plugin
    shortcut: f
    enabled: false

  - import: modules.security.plugin
    shortcut: s
    enabled: false

  - import: modules.phone_drive_safe.plugin
    shortcut: p
    enabled: false